name = "Decisions"
uuid = "56ec2819-4cf1-4b71-8671-a6d58a3a5abb"
authors = ["Mel Krusniak <mel.krusniak@vanderbilt.edu>", "Jackson Wagner <jackson.wagner-1@colorado.edu>", "Kyle Wray <k.wray@northeastern.edu>", "Zachary Sunberg <zachary.sunberg@colorado.edu>", "Tyler Becker <tyler.becker-1@colorado.edu>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ExprTools = "e2ba6199-217a-4e67-a87a-7c52f15ade04"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Distributions = "0.25.120"
ExprTools = "0.1.10"
Parameters = "0.12.3"
Random = "1.11.0"
StaticArrays = "1.9.14"
Test = "1.11.0"
