name = "Decisions"
uuid = "3911d90d-9e38-4fe1-910a-415423006358"
authors = ["Mel Krusniak <mel.krusniak@vanderbilt.edu>", "Jackson Wagner <jackson.wagner-1@colorado.edu>", "Kyle Wray <k.wray@northeastern.edu>", "Zachary Sunberg <zachary.sunberg@colorado.edu>", "Tyler Becker <tyler.becker-1@colorado.edu>"]
version = "0.0.1"

[deps]
DecisionAlgorithms = "24462d87-5a31-4c17-8b3b-e3b0ef9969b3"
DecisionDomains = "b3c2c752-e935-440e-b739-2b15001bb599"
DecisionNetworks = "a1ae968e-b3ba-4546-81a6-f6e3d3a9391a"
DecisionProblems = "b716e576-a1f9-415a-b454-baf909aed799"
DecisionSettings = "c41d4d83-0cc1-4009-96cd-7978f35949ad"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[sources]
DecisionAlgorithms = {path = "DecisionAlgorithms.jl"}
DecisionDomains = {path = "DecisionDomains.jl"}
DecisionNetworks = {path = "DecisionNetworks.jl"}
DecisionProblems = {path = "DecisionProblems.jl"}
DecisionSettings = {path = "DecisionSettings.jl"}

[compat]
Reexport = "1.2.2"
Test = "1.11.0"
