name = "DecisionDomains"
uuid = "b3c2c752-e935-440e-b739-2b15001bb599"
authors = ["Mel Krusniak <mel.krusniak@vanderbilt.edu>", "Jackson Wagner <jackson.wagner-1@colorado.edu>", "Kyle Wray <k.wray@northeastern.edu>", "Zachary Sunberg <zachary.sunberg@colorado.edu>", "Tyler Becker <tyler.becker-1@colorado.edu>"]
version = "0.0.1"

[deps]
DecisionNetworks = "a1ae968e-b3ba-4546-81a6-f6e3d3a9391a"
DecisionProblems = "b716e576-a1f9-415a-b454-baf909aed799"

[sources]
DecisionNetworks = {path = "../DecisionNetworks.jl"}
DecisionProblems = {path = "../DecisionProblems.jl"}